package com.cts.data;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

@DynamoDBTable(tableName = "Teacher")
public class Teacher
{
    private String email;
    private String id;
    private List<Class> classList = new ArrayList<>();

    @DynamoDBAttribute(attributeName = "Email")
    public String getEmail()
    {
        return email;
    }

    public void setEmail(String email)
    {
        this.email = email;
    }

//    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "Id")
    public String getId()
    {
        return id;
    }

    public void setId(String id)
    {
        this.id = id;
    }

    public List<Class> getClassList()
    {
        return classList;
    }

    public void setClassList(List<Class> classList)
    {
        this.classList = classList;
    }
}
